on:
  issues:
    types:
      - opened
      - closed
      - edited
      - deleted
permissions:
  pages: write
  contents: read
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ricardocasares/changelog@main
        with:
          title: Superduper
          description: My blog
      - uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: ${{ github.workspace }}/out/
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
